# Generated by Django 4.2.5 on 2023-09-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='comments',
            field=models.TextField(max_length=2000, verbose_name='Коментарий'),
        ),
    ]
